blank_issues_enabled: false
contact_links:
  - name: Student Exercises
    url: https://github.com/vlad-priscu-globant/movie-app-nov-2025/issues/new/choose
    about: Choose from 28 student collaboration exercises
